CREATE TABLE TASKS
(
    ID      VARCHAR(36)  NOT NULL,
    TITLE    VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    ESTIMATION   VARCHAR(10) NOT NULL,
    DEADLINE   DATE NOT NULL,
    PRIORITY   NUMBER(1) NOT NULL,
    CONSTRAINT PK_TASKS PRIMARY KEY (ID)
);
