CREATE TABLE SUBTASKS
(
    ID      VARCHAR(36)  NOT NULL,
    TASK_ID VARCHAR(36) NOT NULL,
    TITLE    VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    CONSTRAINT PK_TASKS PRIMARY KEY (ID)
);
