spring:
  application:
    name: time-planner
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    username: admin
    password: admin
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show_sql: true
  flyway:
    enabled: true